// <auto-generated />
using System;
using DiaryApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiaryApp.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240908141209_AddedSeedingDataDiaryEntry")]
    partial class AddedSeedingDataDiaryEntry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.7.24405.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiaryApp.Models.DiaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DiaryEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Went hiking with Lisa.",
                            Created = new DateTime(2024, 9, 8, 9, 12, 8, 898, DateTimeKind.Local).AddTicks(4883),
                            Title = "Went Hiking"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Walked Henri and Hugo. Both has massive dumps!",
                            Created = new DateTime(2024, 9, 8, 9, 12, 8, 898, DateTimeKind.Local).AddTicks(5032),
                            Title = "Walked Dogs"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Went to the gym and did some cardio.",
                            Created = new DateTime(2024, 9, 8, 9, 12, 8, 898, DateTimeKind.Local).AddTicks(5035),
                            Title = "Went to the Gym"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Went to the movies and watched a comedy.",
                            Created = new DateTime(2024, 9, 8, 9, 12, 8, 898, DateTimeKind.Local).AddTicks(5037),
                            Title = "Went to the Movies"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Went to the beach and swam in the ocean.",
                            Created = new DateTime(2024, 9, 8, 9, 12, 8, 898, DateTimeKind.Local).AddTicks(5039),
                            Title = "Went to the Beach"
                        },
                        new
                        {
                            Id = 6,
                            Content = "Went to the park and had a picnic.",
                            Created = new DateTime(2024, 9, 8, 9, 12, 8, 898, DateTimeKind.Local).AddTicks(5040),
                            Title = "Went to the Park"
                        },
                        new
                        {
                            Id = 7,
                            Content = "Went to the zoo and saw the animals.",
                            Created = new DateTime(2024, 9, 8, 9, 12, 8, 898, DateTimeKind.Local).AddTicks(5043),
                            Title = "Went to the Zoo"
                        },
                        new
                        {
                            Id = 8,
                            Content = "Went to the museum and saw the exhibits.",
                            Created = new DateTime(2024, 9, 8, 9, 12, 8, 898, DateTimeKind.Local).AddTicks(5045),
                            Title = "Went to the Museum"
                        },
                        new
                        {
                            Id = 9,
                            Content = "Went to the library and read some books.",
                            Created = new DateTime(2024, 9, 8, 9, 12, 8, 898, DateTimeKind.Local).AddTicks(5046),
                            Title = "Went to the Library"
                        },
                        new
                        {
                            Id = 10,
                            Content = "Went to the mall and did some shopping.",
                            Created = new DateTime(2024, 9, 8, 9, 12, 8, 898, DateTimeKind.Local).AddTicks(5048),
                            Title = "Went to the Mall"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
